### PR TITLE
Remove support for EL6 (init scripts)

### PR DESCRIPTION
**Pull request by jouvin**

### CODE REVIEW

**Review by jrha — APPROVED** [review]

**Comment by jouvin** [comment]
Tested successfully at IJCLab (EL9).

**Comment by stdweird** [comment]
this removes support for init.d completly. is this ok, also for el7? and why don't you actually remove the script in src/main/daemon?

**Comment by aka7** [comment]
from what I've noticed, building a package with this PR, I see chkconfig dependency is removed but /etc/init.d/cdp-listend still being installed.  So therefore /etc/init.d dir is being created and I still see the error if chkconfig package is installed later.

```
rpm -qpl target/rpm/cdp-listend/RPMS/noarch/cdp-listend-23.9.0-rc2_SNAPSHOT20240415105908.noarch.rpm
/etc/cdp-listend.conf
/etc/cron.d/check-cdp-listend.cron
/etc/init.d/cdp-listend
/etc/logrotate.d/cdp-listend
/usr/lib/systemd/system-preset/80-cdp-listend.preset
/usr/lib/systemd/system/cdp-listend.service
/usr/sbin/cdp-listend
/usr/sbin/check-cdp-listend
/usr/share/doc/cdp-listend-23.9.0-rc2-SNAPSHOT/ChangeLog
/usr/share/quattor/check-cdp-listend
```

so don't you also need to update pom.xml?
```
diff --git a/pom.xml b/pom.xml
index 2e954ae..480af7b 100644
--- a/pom.xml
+++ b/pom.xml
@@ -129,16 +129,6 @@
               <mapping>
                 <sources>
                   <source>
-                    <location>${project.build.directory}/daemon</location>
-                  </source>
-                </sources>
-                <directory>/etc/init.d</directory>
-                <filemode>755</filemode>
-                <directoryIncluded>false</directoryIncluded>
-              </mapping>
-              <mapping>
-                <sources>
-                  <source>
                     <location>${project.build.directory}/systemd/${project.artifactId}.service</location>
                   </source>
                 </sources>
```
with this change, it does not have any reference to /etc/init.d/cdp-listend in the resulting built rpm.

**Comment by jouvin** [comment]
@aka7 I just pushed the suggested cleanup in pom.xml

**Review by jrha — APPROVED** [review]

**Pull request merged**
